name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: opam-macos-5.3.0

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.3.0'

      - name: Pin
        run: opam pin -n .

      - name: Deps
        run: opam install -ydt . --deps-only

      - name: Build
        run: opam exec -- dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html/
          destination_dir: dev
          enable_jekyll: true
